import Home from "./Home";
import Head from "next/head";

export default function index() {
  return (
    <div>
      <Head>
        <title>Ascend </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./public/favicon.ico" />
      </Head>
      <body>
        <Home />
      </body>
    </div>
  );
}
